apiVersion: apps/v1
kind: Deployment
metadata:
  name: nft-bridge
  labels:
    app: nft-bridge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nft-bridge
  template:
    metadata:
      labels:
        app: nft-bridge
        tier: nft-bridge
    spec:
      containers:
      - name: nft-bridge
        image: liligogo/liligogo/nft-bridge:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: nft-bridge
---
apiVersion: v1
kind: Service
metadata:
  name: nft-bridge
  labels:
    app: nft-bridge
spec:
  type: LoadBalancer
  selector:
    app: nft-bridge
    tier: nft-bridge
  ports:
  - port: 8080
    targetPort: 3001
    protocol: TCP
