apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-depl
  labels:
    app: nodeapp-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp-depl
  template:
    metadata:
      labels:
        app: nodeapp-depl
    spec:
      containers:
      - name: nodeapp-container
        image: liligogo/nodeapp:50
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-svc
  labels:
    app: nodeapp-depl
spec:
  type: LoadBalancer
  selector:
    app: nodeapp-depl
    tier: nodeapp-depl
  ports:
  - port: 8080
    targetPort: 3001
    protocol: TCP
