apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-depl
  labels:
    app: nft-bridge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nft-bridge
  template:
    metadata:
      labels:
        app: nft-bridge
    spec:
      containers:
      - name: nodeapp-container
        image: liligogo/liligogo/nft-bridge:$BUILD_NUMBER
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: nft-bridge-service
spec:
  type: LoadBalancer
  selector:
    app: nft-bridge
  ports:
  - port: 8080
    targetPort: 3001
    protocol: TCP